#!/bin/bash

# Input file (from Task 0)
DATA_FILE="data.json"

# Extract data using jq
NAME=$(jq -r '.name' "$DATA_FILE" | sed 's/.*/\u&/')
HEIGHT=$(jq -r '.height' "$DATA_FILE" | awk '{printf "%.1f", $1/10}')
WEIGHT=$(jq -r '.weight' "$DATA_FILE" | awk '{printf "%.0f", $1/10}')
TYPE=$(jq -r '.types[0].type.name' "$DATA_FILE" | sed 's/.*/\u&/')

# Print formatted output
echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."
